- name: Clone fzf's git repo
  ansible.builtin.git:
    repo: "https://github.com/junegunn/fzf.git"
    depth: 1
    dest: "~/.fzf"
  tags:
    - fzf

- name: Install fzf
  ansible.builtin.command:
    cmd: "./install --bin"
    chdir: "~/.fzf"
  tags:
    - fzf
