# I prefer fnm over nvm.
#
# - name: Install nvm
#   shell:
#     curl -o-
#     https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh
#     | bash
#   args:
#     executable: /bin/bash
#   tags:
#     - node
#     - always

- name: Install fnm
  shell:
    curl -o- https://fnm.vercel.app/install | bash -s --
    --skip-shell
  args:
    executable: /bin/bash
  tags:
    - node
    - always

- name: Install Node.js 18 & 16 using fnm
  shell: |
    export PATH="$HOME/.local/share/fnm:$PATH"
    eval "$($HOME/.local/share/fnm/fnm env --shell zsh --use-on-cd)"
    fnm install 18
    fnm install 16
    fnm default 18
  args:
    executable: /bin/zsh
  tags:
    - node
    - always

- name: Install pnpm globally
  shell: |
    export PATH="$HOME/.local/share/fnm:$PATH"
    eval "$($HOME/.local/share/fnm/fnm env --shell zsh --use-on-cd)"
    npm install -g pnpm
  args:
    executable: /bin/zsh
  tags:
    - node
    - always
